title: Machine Learning and Computer Security Workshop
tagline: co-located with <a href="https://nips.cc/">NIPS 2017</a>, Long Beach, CA, USA, December 8, 2017
email: deep-learning-security@googlegroups.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://machine-learning-and-security.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-relative-links
